### ISSUE TITLE
Why "Temporal frames" is too high value?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#1]
Hello.
I'm impressed by you work. But I have question.
How to make "Temporal frames" value smaller without visible active noise?
When I set 16 -32 I see unstoppable noise.
Can it be fixed?
Thank you

**Comment by gameknife** [comment]
Good question, 
right, 16-32 will be an acceptable temporal frames for realtime game, and that is my **TARGET**.
now I just implement a reproject pass to accumlate samples from previous frame, lack of a another denoise pass.

now I'm doing some researching job to fix it. 

Appreciate your opinion!

**Comment by gameknife** [comment]
I introduce open image denoiser to RayTracing Renderer, with gpu local memory sharing, it will be merge to dev later. set temporal to 8-16 seems a acceptable result, on my rtx3080, it can archive 100fps@1080p in scene #0

**Comment by tigrazone** [comment]
Oh. I dont pike denoisers and prefer simple path tracer

**Comment by tigrazone** [comment]
Is it real to tune up your reproject to remove noise without denoisers? Maybe off reproject task after N frames and use path tracing only?

**Comment by gameknife** [comment]
the open image denoiser is integrated, rebuild from build_windows_oidn.bat, which set WITH_OIDN=1 to cmake, will open denoiser, the render result is perfect at 16-32 temporal frames.

**Comment by gameknife** [comment]
this [fix](https://github.com/gameknife/gkNextRenderer/commits/3d700650b11d8a1a2e28fbd52fcc8630c4bc9a6e) fix a huge bug of reproject. no ghosting if sample exists. scene0 with --samples=4 --temporal=32 get great realtime results

**Comment by tigrazone** [comment]
ok. I will check

**Comment by tigrazone** [comment]
looks great. thank you!!!

**Comment by gameknife** [comment]
@tigrazone hi, I just merge a adaptive samples feature to dev, the result looks perfect!

previously, if miss fetch history, we catchup with a 16 sample ( change to sample * 4 recently ) in one frame, that makes some noise in the miss area.

now, I introduce a adaptive buffer, when missing, I will store a Temporal / 4 count to the buffer, it will decrease every frame, and if it greater than 1, we always catch up with sample * 4 every frame. so the miss area will catchup within Temporal / 4 frame.

the result is perfect!

**Comment by tigrazone** [comment]
Thanks for info. I plan to test it in 2-3 days. Now i'm busy by main work

**Comment by tigrazone** [comment]
Good idea and result is good. 
Take a look to really adaptive sampling. 
https://github.com/berkus/grayzer/blob/work/src/render/ADRender.cpp
Your approach dont analize pixels info changes.

I will implement it and make PR.

**Comment by tigrazone** [comment]
i used this idea from link and have interesting results
http://moo.ho.ua/aaa.html
look at "uniform" and "distributed". 
I used for my experiments SmallVCM on CPU in 2019.
"from 3 to 6 samples per pixel" is minimal and maximal adaptive samples. i.e. 3 is MUST and maximum is 6. usually 4 or 5
Also I checked difference with neightbor pixels - 1 left, right, up, down

**Comment by tigrazone** [comment]
some more results. rendering time is same
without adaptive sampling
![24bpt](https://github.com/gameknife/gkNextRenderer/assets/3808839/262d594a-a5db-46b2-b882-79da6772f7e4)
adaptive sampled
![24bpt-distr](https://github.com/gameknife/gkNextRenderer/assets/3808839/435c3482-0e7d-40f6-b508-b8c080aaa0d9)
---
without adaptive sampling
![4bpt](https://github.com/gameknife/gkNextRenderer/assets/3808839/9cfbb239-560f-45fc-bd68-cdbff6636fb6)
adaptive sampled
![4bpt-distr](https://github.com/gameknife/gkNextRenderer/assets/3808839/31b95b3e-c44a-49a3-aa4b-9fa5cfea1a6e)
---
without adaptive sampling
![9bpt](https://github.com/gameknife/gkNextRenderer/assets/3808839/270e2119-4bfe-4e77-ac90-62c8829a1d0b)
adaptive sampled
![9bpt-distr](https://github.com/gameknife/gkNextRenderer/assets/3808839/3b77ad5c-ad6f-44e1-b227-e4373593e407)
---
without adaptive sampling
![12bpt](https://github.com/gameknife/gkNextRenderer/assets/3808839/864b5dd8-d2b8-4c43-b291-aa7c811509e8)
adaptive sampled
![12bpt-distr](https://github.com/gameknife/gkNextRenderer/assets/3808839/8dfeaf7b-4625-475d-bc2f-79158e8699d4)
---
without adaptive sampling
![18bpt](https://github.com/gameknife/gkNextRenderer/assets/3808839/9cb292f6-41c5-4aed-a63a-1f3069e9fdaf)
adaptive sampled
![18bpt-distrib](https://github.com/gameknife/gkNextRenderer/assets/3808839/70540971-1913-4391-8495-9ee58635a648)
---
without adaptive sampling
![19bpt](https://github.com/gameknife/gkNextRenderer/assets/3808839/4d285c25-baa0-4698-bf81-611945e2e7db)
adaptive sampled
![19bpt-distr](https://github.com/gameknife/gkNextRenderer/assets/3808839/dc2ba4b6-38b1-4e8a-81fd-847bcb9d565d)

**Comment by gameknife** [comment]
> Good idea and result is good. Take a look to really adaptive sampling. https://github.com/berkus/grayzer/blob/work/src/render/ADRender.cpp Your approach dont analize pixels info changes



> Good idea and result is good. Take a look to really adaptive sampling. https://github.com/berkus/grayzer/blob/work/src/render/ADRender.cpp Your approach dont analize pixels info changes



> Good idea and result is good. Take a look to really adaptive sampling. https://github.com/berkus/grayzer/blob/work/src/render/ADRender.cpp Your approach dont analize pixels info changes

Thanks, it will helps, currently, I only judge pixel by "object instanced id & material id", so specular or reflection detail will accumulate in-correct, I will ref this implement.

**Comment by tigrazone** [comment]
from 1 sample per pixel switch to 16 samples for pixel is too much.
from 1 samples to 4 like I do is ok.
dont do oversampling. be smart, not bruteforce

**Comment by tigrazone** [comment]
maybe it interesting for you https://www.iliyan.com/publications/ResidualPathIntegral

**Comment by tigrazone** [comment]
I have an idea how not to tweak variance paramerter. 
find variance of neightbor pixels and compare cheanges of variance
avg = sum of variances of neightbor pixels / pixels
current variance difference is a peak value of current/avg from 0 to 1 - and this value can be tweaked in UI
0.1 - 0.4 is enough to start adaptive sampling

**Comment by gameknife** [comment]
> I have an idea how not to tweak variance paramerter. find variance of neightbor pixels and compare cheanges of variance avg = sum of variances of neightbor pixels / pixels current variance difference is a peak value of current/avg from 0 to 1 - and this value can be tweaked in UI 0.1 - 0.4 is enough to start adaptive sampling

try it tonight～
