### ISSUE TITLE
is an issue with primitiveId and Ray.Distance?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#103]
I see strange things with primitiveId in code
https://github.com/gameknife/gkNextRenderer/blob/6fd536815c932c058c273c2a5eb6d5e89c30c412/assets/shaders/RayQuery.comp#L60
next set of primitiveId is on line
https://github.com/gameknife/gkNextRenderer/blob/6fd536815c932c058c273c2a5eb6d5e89c30c412/assets/shaders/RayQuery.comp#L114
and in FetchPrimaryRayInfo() we just copy value of Ray.primitiveId 
https://github.com/gameknife/gkNextRenderer/blob/6fd536815c932c058c273c2a5eb6d5e89c30c412/assets/shaders/common/RTCommon.glsl#L132

in void ProcessMiss(const vec3 RayDirection) we see
https://github.com/gameknife/gkNextRenderer/blob/6fd536815c932c058c273c2a5eb6d5e89c30c412/assets/shaders/common/RTCommon.glsl#L39

why in assets/shaders/RayQuery.comp line 60 set not "miss" i.e. 65535 << 16 | 0 BUT set 0?
0 is legal object id and can make side effects.

one more strange with Ray.Distance
in void ProcessMiss(const vec3 RayDirection)
https://github.com/gameknife/gkNextRenderer/blob/6fd536815c932c058c273c2a5eb6d5e89c30c412/assets/shaders/common/RTCommon.glsl#L41
but here check is strange
https://github.com/gameknife/gkNextRenderer/blob/6fd536815c932c058c273c2a5eb6d5e89c30c412/assets/shaders/common/RTCommon.glsl#L131
because when Ray.Distance < -5 ? NEVER. because never Ray.Distance set to negative number.

Maybe legal to set in ProcessMiss() Ray.Distance = -6 and in RayQuery.comp line 60 set primitiveId = 65535 << 16
or maybe primitiveId = ~0 for ray miss?

**Comment by gameknife** [comment]
it is an old workaround for the miss situration ( 'hit' the skybox), and primitiveid currently is only for reproject, so, make the sky 65535, always use current frame color
