### ISSUE TITLE
questions about nodes

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#108]
1. why you hardcoded 65535 and not use real number of nodes?
https://github.com/gameknife/gkNextRenderer/blob/d6e4d0afda26662c65c0c611b303541f609dfa15/src/Assets/Scene.cpp#L115-L116
2. why you not set and not use materialId in NodeSimpleProxy?
3. After add NodeSimpleProxy the renderer slows down up to 15%. Can be removed slow down? I like your renderer because it was incredibly fast
4. You update nodes EVERY frame. WHY? Maybe this piece of code slows down renderer. Maybe better update once and just use and update on demand
https://github.com/gameknife/gkNextRenderer/blob/d6e4d0afda26662c65c0c611b303541f609dfa15/src/Vulkan/VulkanBaseRenderer.cpp#L597

**Comment by gameknife** [comment]
some framework code is robust, for the MagicaLego Demo. All things are in basic stage, I support dynamic scene first, then optimize them. Still things will not impact on nodes updates. And the update time can optimized.

**Comment by gameknife** [comment]
still scene's not update now, fix in https://github.com/gameknife/gkNextRenderer/commit/36b61f2fd717a324a74115ab5cde821f70be281f
