### ISSUE TITLE
feature request: use tangents in ggx calculation

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#111]
please rewrite code with loaded from gltf file tangents or if absent - recreated by mikktspace

**Comment by tigrazone** [comment]
Can you finish this part of renderer?
And for use tangent with ggx calculations

**Comment by tigrazone** [comment]
Maybe this code can help

https://github.com/nvpro-samples/vk_gltf_renderer/blob/5a02beb1e28d05d652201a1c47409f4f5168745f/shaders/get_hit.h#L41-L102

**Comment by gameknife** [comment]
it is currently behaviour
