### ISSUE TITLE
error C2065: 'img_encoded': undeclared identifier - compile WITH_AVIF=1

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#113]
C:\msys64\home\tigra\gkNextRenderer\src\Runtime\BenchMark.cpp(270,9): error C2065: 'img_encoded': undeclared identifier
 [C:\msys64\home\tigra\gkNextRenderer\build\windows\src\gkNextEditor.vcxproj]

**Comment by tigrazone** [comment]
fix is [here](https://github.com/gameknife/gkNextRenderer/pull/114)

**Comment by gameknife** [comment]
You can follow my main branch. it will be more stable, I will add more build case in main branch.
I will fix this issue on dev later. Thx!
