### ISSUE TITLE
feature request: materialId in nodes

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#120]
it is good to implement store materialId not in Vertex like now but in NodeSimpleProxy.
and it can be more compact to store on gpu.
as I see NodeSimpleProxy contains materialId. 
maybe time to use it?

**Comment by gameknife** [comment]
Yes, plan to change the mesh's materialid into a offset, then map to the real materialid in nodes. So it can change the materials in runtime.

**Comment by tigrazone** [comment]
When it can be done? This week? Month?

**Comment by tigrazone** [comment]
Can you put this task to top of the to-do list?
Very needed

**Comment by tigrazone** [comment]
Why you use 4 matids for one plane?
Why not 1 matid fir 3 vertices(one plane).
Material changed only for whole mesh.
Obj meshes can be sorted by material

**Comment by gameknife** [comment]
one "model" may contain face with multiple material id, I changed the previous directly matid into a idx, fetch the real matid from node.
currently, livingroom, still, kitchen scene, has some model with more than 1 materials.

But sure, I can divided the model into multiple parts for single mat, but it will split the topology, may break the original node-model structure before, I'm considering this change.

**Comment by tigrazone** [comment]
You are right about model.
But one primitive in model use one material. 
Is it possible to use instances not with whole model, but with one primitive?
If yes - my idea is can be ok.
Then only one materialId can be used for one instance. Not 4, not 16. Only one

**Comment by gameknife** [comment]
I have considered this question, currently, it only waste 32 bit in vertex, it can be compressed to 8bit.
But other things goes more convienient, I will keep this design for now

**Comment by tigrazone** [comment]
Dont understand how you plen to compress.
It can work also with huge models w/o 8 bit overflow?
Show me.
If not, 1 uint for materialId per instance/primitive can be good approach

**Comment by gameknife** [comment]
currently, vertex size is 3 + 3 + 4 + 2 float, 1 uint, 52bytes,
it can compress to at least 35bytes, 1 byte of the material subidx is 1 / 35 cost

**Comment by gameknife** [comment]
the feature branch: https://github.com/gameknife/gkNextRenderer/tree/feature/compress_gpuvertex
compress a gpuvertex, saved about 200mb+ gpumem of the still.glb

vertex size from 52 bytes -> 32bytes, the material index only takes 2bytes, there still have 2 of 32 bytes can save other infomation.

**Comment by tigrazone** [comment]
Data compression is good thing ;-)

**Comment by tigrazone** [comment]
Is it possible to use ONE materialId for node?
Just use one material for primitive
