### ISSUE TITLE
Bin\vulkan-1.dll

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#125]
It is not good - copy vulkan -1.dll to bin folder and need it on start of program.
If vulkan -1.dll is absent in folder of exe file - program cant start.
Better way - use vulkan-1.dll from system.
One more side of problem - wrong version of this dll.

Request:
1. Use vulkan-1.dll from system
2. Dont copy and need to use dll to bin folder

**Comment by gameknife** [comment]
I think there is no problem.

if vulkan-1.dll is absent, it use my system's vulkan-1.dll instead.
copy the build version of vulkan-1.dll seems a official way to ensure the version of vulkan?

you can search the vulkan-1.dll in your computer, it seems every software takes one, differ by vulkan sdk version

**Comment by tigrazone** [comment]
If where is no vulkan-1.dll in bin folder where .exes placed, program sometimes fails and can run when add vulkan-1.dll to this folder. Dont find in system

**Comment by tigrazone** [comment]
Other programs dont need vulkan-1.dll in folder with .exes
Maybe it can be possible to not place vulkan-1.dll and use from system?

**Comment by gameknife** [comment]
almost every software takes one, and with its own version
![image](https://github.com/user-attachments/assets/722c0f34-41b4-4d72-8e34-4277201335a6)

**Comment by tigrazone** [comment]
> almost every software takes one, and with its own version ![image](https://private-user-images.githubusercontent.com/2137741/394073009-722c0f34-41b4-4d72-8e34-4277201335a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTM5MjksIm5iZiI6MTczMzgxMzYyOSwicGF0aCI6Ii8yMTM3NzQxLzM5NDA3MzAwOS03MjJjMGYzNC00MWI0LTRkNzItOGUzNC00Mjc3MjAxMzM1YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMDY1MzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFmNGI3MWE5ZDYwNjI0ZjFhNjQ4NWJjMTM1OTI2ZjVjYTY1ZWIzM2YxNmZiNzk0MzE5YWNlZjcwYjEyMjg5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pcJLR4noRnK9xEAFVsMTxOy7yqWqZttcyQFtiaChHCs)

I don't understand what you mean.
If it written somehow in code "for start need to be in bin folder vulkan-1.dll elsewhere dont start" please remove it. Then program can find this dll from PATH variable

**Comment by gameknife** [comment]
> It is not good - copy vulkan -1.dll to bin folder and need it on start of program. If vulkan -1.dll is absent in folder of exe file - program cant start. Better way - use vulkan-1.dll from system. One more side of problem - wrong version of this dll.
> 
> Request:
> 
> 1. Use vulkan-1.dll from system
> 2. Dont copy and need to use dll to bin folder

Just answer these 2 request: 

1. cannot use vulkan-1.dll in PATH, it maybe not exist, also, it will mismatch the vulkan sdk we use
2. the build system will copy it from vulkansdk path to "bin path", its not a problem.
