### ISSUE TITLE
kitchen and still scenes rendered as broken after last commit

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#126]
![kitchen-broken](https://github.com/user-attachments/assets/e0f065c8-439b-4b34-9794-8d43b00a6b80)
![still-broken](https://github.com/user-attachments/assets/c3b4f61f-52ce-48c3-8f34-5bf85ee4edc5)

**Comment by gameknife** [comment]
new feature branch is developing the full scene node struture, these issues will be fix after it merge to dev

**Comment by gameknife** [comment]
merged to dev & main
