### ISSUE TITLE
How to reload mesh?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#130]
1. One idea is load mesh and textures in parallel and show as is and calculate tangents in parallel with mikktspace. After calculate tangents for every mesh I want to reload Vertex data. How?
2. Second idea is same but processing tangents on gpu. And after change every mesh I want to reload mesh data
P.s. absent tangents before finish tangents calculations I can temporarily calculate by Onb() and after calculate finish use calculated tangents data

**Comment by gameknife** [comment]
Currently, there's no mesh streaming needs. So all mesh prepared on threaded scene loading.

I have a far plan to load a mass scene (8km x 8km) to test the ray tracing on large scale, I may consider the streaming for mesh, tangent calculation is not the key issue, speed is not the key issue. But the storage buffer use to store mesh data now need to take care.

**Comment by tigrazone** [comment]
Can you reply to my question? 
How to reload mesh data if i change vertex data?

**Comment by gameknife** [comment]
> Can you reply to my question? How to reload mesh data if I change vertex data?

Change the vertex data in model, then, update the vertex & indices storage in scene.

**Comment by tigrazone** [comment]
Can you show me this in code?
Which functions I must call for this?

**Comment by tigrazone** [comment]
Is it enough to set scene is dirty?

**Comment by gameknife** [comment]
> Can you show me this in code?
> Which functions I must call for this?

There's no imlement about realtime mesh update, the animation is only update the scene nodes and TLAS

**Comment by tigrazone** [comment]
Can you do functions to implement this?

**Comment by gameknife** [comment]
tangent now is import from gltf if exist, or will generate with mikktspace.
And the materialId is start to implement, this will be a big change, I will do some refactor work at first

**Comment by tigrazone** [comment]
I say about parallel tangent calc because it works slow. Do it in parallel not a big problem but resend mesh data is a problem. Maybe I refactor code somehow
