### ISSUE TITLE
feature request: use wuffs vs stb_image

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#138]
wuffs loads images faster.
stb_image can be used for hdr load

**Comment by gameknife** [comment]
stbi is lightweight
and now, only first met non ktx texture will use stbi to decode, then a ktx cache will build, next time, loading time and memory is super low.

**Comment by tigrazone** [comment]
Png is loaded 2.5 times faster with wuffs

**Comment by gameknife** [comment]
> Png is loaded up to 1.5 - 2.5 times faster with wuffs

when first met, the png will be encoded to cache/hash.ktx, then, next time you try to load this texture, it will directly load gpu compressed texture

**Comment by tigrazone** [comment]
Interesting feature. When you plan to implement?

**Comment by gameknife** [comment]
> Interesting feature. When you plan to implement?

already merge to dev, have a try
