### ISSUE TITLE
Feature request: refactor raytracing cycle of bounces with for operator

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#17]
Please refactor cycle of bounces with for operator.
I'm trying but have issues in quality and result of rendering.
I plan to implement MIS and full path tracing with NEE(Next event estimation).
Pease help

**Comment by tigrazone** [comment]
Benefits:
- smaller spv file. because defines just make copies of code
- clearer code
- easier to extend

**Comment by gameknife** [comment]
ok，i will put this on 1st priority, and also provide a equal rayquery pipeline

**Comment by tigrazone** [comment]
> equal rayquery pipeline
maybe move common code to separate file like authors of vk_raytrace do https://github.com/nvpro-samples/vk_raytrace
https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/pathtrace.glsl
raytracing pipeline - https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/pathtrace.rgen
rayquery pipeline - https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/pathtrace.comp

**Comment by gameknife** [comment]
> > equal rayquery pipeline
> maybe move common code to separate file like authors of vk_raytrace do https://github.com/nvpro-samples/vk_raytrace
> common code - https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/pathtrace.glsl
> raytracing pipeline - https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/pathtrace.rgen
> rayquery pipeline - https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/pathtrace.comp
> 

yes, code will in common file except the control framework

**Comment by gameknife** [comment]
currently, rayquery pipeline is ok to use, I will catchup the reproject pass later.
the performance is more faster than raytracing pipeline, 
guess that multi shader binding and payload transfer is the problem!

I think the new ray query rendereris a better choise to impl next features~

**Comment by tigrazone** [comment]
rayquery pipeline is NOT ok now. renders not similar. scene "Ray Tracing In One Weekend" for example, grayed. without balls

**Comment by tigrazone** [comment]
I just wait for you finish with RayQuery - reprojection and so

**Comment by gameknife** [comment]
> I just wait you add to RayQuery reprojection and make it work same as RayTracing pipeline

I'm working on it, RayQuery Pipeline will be ok in few days. Procedural Hit not handled currently,

**Comment by gameknife** [comment]
> I just wait you add to RayQuery reprojection and make it work same as RayTracing pipeline

reproject is ok, procedural hit is on the way.
rq pipe is huge faster than rt pipe, I will find the different...

**Comment by tigrazone** [comment]
I know about rq speedup. 
I compare speed of rendering with vk_shaded_gltfscene and your renderer on luxball scene.
With raytracing pipeline on both renderers and with  --present-mode 0
Your renderer 20fps, vk_shaded_gltfscene 139fps on my rtx 3060.
Something makes renderer too slow

**Comment by tigrazone** [comment]
With rayquery pipeline scene "Ray Tracing In One Weekend" rendered like gray plane
![rtow-gray1](https://github.com/gameknife/gkNextRenderer/assets/3808839/73faa8a3-f428-4d1f-8935-f9bcf48b696f)

**Comment by gameknife** [comment]
> With rayquery pipeline scene "Ray Tracing In One Weekend" rendered like gray plane ![rtow-gray1](https://private-user-images.githubusercontent.com/3808839/345039763-73faa8a3-f428-4d1f-8935-f9bcf48b696f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzA5MzksIm5iZiI6MTcxOTkzMDYzOSwicGF0aCI6Ii8zODA4ODM5LzM0NTAzOTc2My03M2ZhYThhMy1mNDI4LTRkMWYtODkzNS1mOWJjZjQ4YjY5NmYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMTQzMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTFiZDZiZWRmMDVkZDI4MDY2NWZlOGJlOTFjNTNmOThmNzU3MmNlNjUxYTlkYTk4ZjQ5ZTZhYzZmZDVjYjMxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p_eymIXo2W7Pr8WOiCZUD3OvIOLUYHJnQLAnjDWrbyM)

this is a full procedural scene, that makes the code complex, I will think about if really need to support it.

**Comment by gameknife** [comment]
> I know about rq speedup. I compare speed of rendering with vk_shaded_gltfscene and your renderer on luxball scene. With raytracing pipeline on both renderers and with --present-mode 0 Your renderer 33fps, vk_shaded_gltfscene 129fps on my rtx 3060. Something makes renderer too slow

luxball has big area of ScatterDieletric material, if u change it to Lambertian, my 4070 fps boost from 45 -180fps @ 1080p, the render resulte of ScatterDieletric of vk_shaded_gltfscene seems not right, my impl is almost the same with blender's cycles render

**Comment by gameknife** [comment]
> > I know about rq speedup. I compare speed of rendering with vk_shaded_gltfscene and your renderer on luxball scene. With raytracing pipeline on both renderers and with --present-mode 0 Your renderer 33fps, vk_shaded_gltfscene 129fps on my rtx 3060. Something makes renderer too slow
> 
> luxball has big area of ScatterDieletric material, if u change it to Lambertian, my 4070 fps boost from 45 -180fps @ 1080p, the render resulte of ScatterDieletric of vk_shaded_gltfscene seems not right, my impl is almost the same with blender's cycles render

if i change to 720p without adaptive sample, fps boost from 100fps -> 400fps

**Comment by gameknife** [comment]
> > I know about rq speedup. I compare speed of rendering with vk_shaded_gltfscene and your renderer on luxball scene. With raytracing pipeline on both renderers and with --present-mode 0 Your renderer 33fps, vk_shaded_gltfscene 129fps on my rtx 3060. Something makes renderer too slow
> 
> luxball has big area of ScatterDieletric material, if u change it to Lambertian, my 4070 fps boost from 45 -180fps @ 1080p, the render resulte of ScatterDieletric of vk_shaded_gltfscene seems not right, my impl is almost the same with blender's cycles render

finally, I add adaptive sample for material, the metal and glass will gain more samples, and that is always enable, even if adaptive sample set to false. fix it in the latest commit. check the performance when adaptive sample disabled.

**Comment by tigrazone** [comment]
Light sampling maybe add slowness.
As usual it can be a oart of next event estimate(NEE) process with MIS

**Comment by tigrazone** [comment]
I check new commits with rayQuery. it is very fast. thank you!

**Comment by tigrazone** [comment]
I check new commits with rayQuery. it is very fast. thank you!

**Comment by tigrazone** [comment]
> With rayquery pipeline scene "Ray Tracing In One Weekend" rendered like gray plane ![rtow-gray1](https://private-user-images.githubusercontent.com/3808839/345039763-73faa8a3-f428-4d1f-8935-f9bcf48b696f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDg3NzAsIm5iZiI6MTcyMDcwODQ3MCwicGF0aCI6Ii8zODA4ODM5LzM0NTAzOTc2My03M2ZhYThhMy1mNDI4LTRkMWYtODkzNS1mOWJjZjQ4YjY5NmYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTQzNDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M2MTNkZTRlYmQzYjk2YmEyZTE1YmY0YzQ1MDUyZmNmNjdkYTlkNmQ4YjYwNzFiMWE4ZmI2YTcwYzI0MmE3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HdXdKx7wGt9PQ85Nb9LEV4CveULMTKaVkvjzcctS1cc)

can you make support of procedural scenes for rayQuery?
it can be useful
