### ISSUE TITLE
wrong renders after refactor RayTracing.rgen

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#19]
scenes
"LowpolyTrack"
"Simple"
"Complex"
"Ray Tracing In One Weekend"
now renders wrong and overbright.
Maybe other scenes also renders wrong

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/5c67a7885cd30ed81fcf555a55880d211d7f9674

**Comment by gameknife** [comment]
affect sunlight scene, it will return early than other lightray, so atten with diffuse early.
