### ISSUE TITLE
still scene

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#22]
Can you add to repo this scene?
![Alt text](https://github.com/gameknife/gkNextRenderer/raw/main/gallery/Still.avif "still")

**Comment by tigrazone** [comment]
is this scene available and did you can add it to repository?

**Comment by gameknife** [comment]
added, with compressed mesh cost 19mb

https://github.com/gameknife/gkNextRenderer/blob/dev/assets/models/still.glb
