### ISSUE TITLE
import glbs

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#23]
I'm importing glb to another raytracer and glass not imported ok.
![image](https://github.com/gameknife/gkNextRenderer/assets/3808839/bb908651-6415-4575-bfc6-489e9c7ce47e)
how to support these glass? can you change scene with extra: "glass"?

For luxball scene I find in code 
https://github.com/gameknife/gkNextRenderer/blob/b90eb1324c4d8c98cece9128641ad0f1c388fc24/src/Assets/Model.cpp#L245-L248
and do in my renderer code
```
    if(tmat.extras.Has("glass"))
    {
      gmat.ior.ior = 1.46f;
      gmat.transmission.factor = 1.0f;
    }
```
![image](https://github.com/gameknife/gkNextRenderer/assets/3808839/c21e3e2e-f395-4f11-80e8-5ff4ad69e456)
![image](https://github.com/gameknife/gkNextRenderer/assets/3808839/b70ca586-120b-45b4-bfaa-9c2a9c8ce166)

**Comment by tigrazone** [comment]
maybe is more correct way is set ior and transmissionFactor?
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_ior/README.md
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_transmission/README.md

**Comment by gameknife** [comment]
my source scene is edit in blender, I will check if it can export ior and transmission

**Comment by gameknife** [comment]
updated three glb to export ior & transmission, and update the model.cpp

**Comment by tigrazone** [comment]
Thank you!

**Comment by tigrazone** [comment]
For which purposes you plan to use RefractionIndex2?

**Comment by gameknife** [comment]
> For which purposes you plan to use RefractionIndex2? Why not RefractionIndex?

specific for qx50 scene, the car glass is single layered, ior2 make the refraction ray pass through directly~ a trick, with extra

**Comment by tigrazone** [comment]
looks like thinwalled
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_volume/README.md
thicknessFactor 
```
  // Thin film approximation
  if(mat.thicknessFactor == 0.0F && mat.roughness > 0.0F)
  {
    refractedDir = sampleThinTransmission(data, mat);
  }
  else
  {
    refractedDir = sampleSolidTransmission(data, mat, refracted);
  }
```
https://github.com/nvpro-samples/nvpro_core/blob/a3990a04a9769f3bc6b59a915b0078c32e786d34/nvvkhl/shaders/bsdf_functions.h#L197-204

**Comment by tigrazone** [comment]
better way to set bool thinWalled = material.thicknessFactor < 0.011;
because precission issues
and I rewrite in by fork repo
`if(mat.thinWalled && mat.roughness > 0.0F)`

**Comment by tigrazone** [comment]
maybe dielectrics works wrong. because when I just open qx50.glb and start to render by https://github.com/nvpro-samples/vk_shaded_gltfscene and glass rendered w/o issues.
![q50](https://github.com/gameknife/gkNextRenderer/assets/3808839/6cc5db16-232f-4f25-a2c3-607897f0ac41)

I use previous version of vk_shaded_gltfscene and nvpro_core bacause new version have issues

**Comment by tigrazone** [comment]
kitchen scene has strange glass material
![kitchen1](https://github.com/gameknife/gkNextRenderer/assets/3808839/e3dc5001-9ad3-482f-b2f4-8748d53dc93a)
