### ISSUE TITLE
Scene files doenst load outside assets folder

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#27]
After last dev commit renderer doesnt load scene files outside assets folder.
After my commit, renderer can load scene files from everywhere

**Comment by gameknife** [comment]
consider the android filesystem, see Utilities::FileHelper::GetPlatformFilePath

**Comment by tigrazone** [comment]
I mean not android build.
If you choose to open scene outside assets folder then file not been opened

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/07c7a60070cb65b999e57cae5de0a5d63f380caf
