### ISSUE TITLE
Broken csv info save

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#28]
in this line after your change buffer not set
https://github.com/gameknife/gkNextRenderer/blob/ae63b6f4c98d7edc337a48d651a0b34f8b6e4e44/src/Application.cpp#L454
in previous version with sprintf() buffer was filled with needed data

**Comment by gameknife** [comment]
the fps text not fill in buffer any more, I will refactor this csv report logic tonight~

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/07c7a60070cb65b999e57cae5de0a5d63f380caf
