### ISSUE TITLE
what FlattenVertices() really do and how it works?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#35]
and why need to use it?

**Comment by gameknife** [comment]
the renderer contain visibility buffer rendering need this, current rasteriaze pipeline, shared vertice cannot contain triangle id, so have to split vertice, is it break performance or something? there may be a way, but its not a prority task to find it.

**Comment by tigrazone** [comment]
> it break performance or something?

no, just interesting
