### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#37]
Hello.
I implement all about show cameras list and change current camera index in 
https://github.com/tigrazone/gkNextRenderer/commit/98294cb2b8642cd92a91fa891ab0c33446092a44
but I cant implement ModelView change - have errors of compiler in
https://github.com/tigrazone/gkNextRenderer/blob/98294cb2b8642cd92a91fa891ab0c33446092a44/src/Application.cpp#L74-L78
Please help to resolve

**Comment by tigrazone** [comment]
Glb with many camesras
https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ToyCar/glTF-Binary

**Comment by gameknife** [comment]
I will impl camera list later in dev
currently I implement a camera focus feature, raycast in gpu, and readback to cpu, it will merge to dev later.

**Comment by tigrazone** [comment]
fixed by mutable
