### ISSUE TITLE
how to reproduce "Planets In One Weekend", "Lucy In One Weekend", "Cornell Box & Lucy" with your framework?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#4]
I'm trying to add transforms on node creation and it works.
but how to appoint textures?

**Comment by gameknife** [comment]
like the Model::LoadGLTFScene do,
push it to textures, and make the id correct in matierial

currently, all texture are bindless, it store in a global texture lists, reference by id in material

**Comment by tigrazone** [comment]
Can you show me in code?
I try but cant attach textures to node
