### ISSUE TITLE
What is AutoFocus feature and how it works?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#41]
Can you implement AutoFocus also for RayTracing pipeline, not only for RayQuery?

**Comment by gameknife** [comment]
okay, soon

**Comment by gameknife** [comment]
add in https://github.com/gameknife/gkNextRenderer/commit/0d71e7ff8e6048d4b01409aac12532633ac4ac54

**Comment by tigrazone** [comment]
Thank you.
Is raytracing pipeline obsolete now?

**Comment by gameknife** [comment]
rayquery pipeline is more flexible, and also cross-platform method, I will pay more attention on this.
raytracing pipeline have some limit.

**Comment by tigrazone** [comment]
maybe better to do autofocus on cursor position and SPACE press like done in vk_raytrace?
https://github.com/nvpro-samples/vk_raytrace/blob/12d147d8df988bdf528adb3c9c6868f03dc4fd2b/src/sample_example.cpp#L469

**Comment by gameknife** [comment]
change in [bb2c2e3]

**Comment by tigrazone** [comment]
You do it better. When I push a space box is showen and faster leave. It is not error?
I mean to use space on mouse position. 
Not on center of screen

**Comment by gameknife** [comment]
> You done it better. When I push a space box is shown and fast leave. It is not error? I mean to use space on mouse position. Not on center of screen

hold space into a auto focus mode, move your camera, it will focus every frame.
