### ISSUE TITLE
Feature request. Parallel texture load

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#46]
Is it possible to load textures asynchronous, in parallel?

**Comment by gameknife** [comment]
Yes, I plan to make the loading works on threadtask and don't stuck the main thread, texture loading task may be the first one to implement.

**Comment by gameknife** [comment]
progress updated. working on a task facility for resource loading and thread separating, I get to clinic these days, so someting delayed, the task facility will be in use within this week~

**Comment by tigrazone** [comment]
it pleases. get well

**Comment by gameknife** [comment]
finally done on https://github.com/gameknife/gkNextRenderer/commit/4dded507f8b6c7ba30c9517182d5bb3ec845d3d3
all texture process on thread, I refactor a global bindelss texture pool, and submit all texture resources on an new vkQueue.
I tested on a huge scene with hundres textures, texture completed one by one at realtime

**Comment by tigrazone** [comment]
Works good.
Can you shortly describe what you changed and how it all works.
I see now not shown filenames of loaded textures
