### ISSUE TITLE
low GPU usage

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#48]
when I use renderer in RayTracing or RayQuery modes I have max 80-85% of GPU usage, in some scenes max 60-70% gpu usage. It's too low.
How to make GPU usage more, up to 95-99% ?
I use rtx 3060

**Comment by tigrazone** [comment]
It is screenshot with tests of my other renderer.
Gaps on graph is time to start of tests
![645](https://github.com/user-attachments/assets/706f7ad9-97eb-44ad-8954-3d94b80d4588)

**Comment by tigrazone** [comment]
in realtime
https://www.youtube.com/watch?v=oKNN8lnEk64

**Comment by gameknife** [comment]
it may depends on scenes, rt core has special hardware instead of cuda core, may cause stall on some scenerios, I think.

**Comment by tigrazone** [comment]
I think code have bottlenecks. If you test original https://github.com/GPSnoopy/RayTracingInVulkan you can see it utilizes up to 100% of GPU

**Comment by gameknife** [comment]
it could be figure out by using gpu profile tools like NSight

**Comment by tigrazone** [comment]
Can you do renderer more effective utilize GPU? Now it works slow and it is not good

**Comment by gameknife** [comment]
I will do some check these days, did you realized that slower than which specific version?
I doubt about the "gpu raycast code", it may synchronus gpu with cpu, it will give gpu a break before tick begins.

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/58bf6a5935a9d864afd12eb7ac0172a811d0b9ab
previous gpu-raycast use a cpu <-> gpu buffer copy mechanic, its not a good option. change to host-cohrent memory.
currently, the complex.glb gpu load higher from 78% -< 95%. framerate from 400fps -> 600fps

**Comment by tigrazone** [comment]
thank you. works really faster.
maybe research one more bottleneck and make fastest!
