### ISSUE TITLE
renderers

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#5]
please discribe renderers types and features of every renderer:
0: RayTracingRenderer
1:  ModernDeferredRenderer
2: LegacyDeferredRenderer
3: RayQueryRenderer
4: HybridDeferredRenderer
5: VulkanBaseRenderer

**Comment by gameknife** [comment]
gkNextRenderer's targeting realtime rendering. currently i impl this 6 renderers, some for learning realtime raytracing, some for performance comparasion. I will explain the usage of them in comments later.

**Comment by gameknife** [comment]
**0: RayTracingRenderer**
A Groundtruth Path Tracing Renderer, targeting the ground truth result.

** 1: ModernDeferredRenderer **
A Experimental Renderer, basic implement of visibility buffer rendering, targeting performance benchmark.

** 2: LegacyDeferredRenderer **
A Experimental Renderer, basic implement of traditional gbuffer rendering, targeting performance benchmark.

** 3: RayQueryRenderer **
A RayQuery version of RayTracingRenderer, targeting support RayTracing on PC / Android / Mac / iOS, still a startup, will functional after a full-scope refactored.

** 4: HybridDeferredRenderer **
A HybridRenderer based on ModernDeferredRenderer, targeting support high-performance raytracing hybrid with traditional render method, currently provide 1~2 ray / pixel, runs on Android device with interactive framerates.

** 5: VulkanBaseRenderer **
A Basic Forward Renderer, the base class of all above, provide a simple render pipeline.

**Comment by tigrazone** [comment]
Thank you for explaination
