### ISSUE TITLE
coloring esc codes doesnt work on my Windows 10 machine

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#50]
![image](https://github.com/user-attachments/assets/63b0395c-3ffe-4b59-8388-4b348488b5a0)

**Comment by tigrazone** [comment]
[this](https://www.codeproject.com/Tips/5255355/How-to-Put-Color-on-Windows-Console) helps me.
but how to make this workable w/o admin rights and command in console?

**Comment by gameknife** [comment]
console in new "windows terminal", linux / macos works fine, it is a generally cross platform log format, I don't want to workaround on windows's old console~

**Comment by tigrazone** [comment]
maybe is good to add to Windows only
```
HANDLE hOutput = GetStdHandle(STD_OUTPUT_HANDLE);
DWORD dwMode;
    GetConsoleMode(hOutput, &dwMode);
    dwMode |= ENABLE_PROCESSED_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    SetConsoleMode(hOutput, dwMode);
```

from [here](https://stackoverflow.com/questions/52607960/how-can-i-enable-virtual-terminal-processing)

**Comment by tigrazone** [comment]
done in https://github.com/gameknife/gkNextRenderer/pull/49/commits/2864094a8baff62a9a39d36bae92dd4101b2cb9c

**Comment by gameknife** [comment]
merged pr
