### ISSUE TITLE
first scene not seen when renderer start

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#51]
before I select some scene in selector I see black window.
After of 1st select scene all works ok
![00001](https://github.com/user-attachments/assets/e31b7c6e-ce57-43e7-a2e4-d83a683eb644)

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/dfd0e5efdcb1576463ee9c1682b92b992f79198c
