### ISSUE TITLE
I try to drop glb to renderer. Materials and textures imported WRONG

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#52]
![drop-glb1](https://github.com/user-attachments/assets/3f4a7a6d-f9b5-4f81-b893-e5d4425b060d)

**Comment by gameknife** [comment]
it looks like read the normal map as a basecolor map?

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/883152cf5420e72384fcddf0c7cbbcec1d52bd7b
the texture name empty, so all texture goes into one. fixed.

**Comment by tigrazone** [comment]
now is ok
