### ISSUE TITLE
benchmarks is broken. threads problem

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#54]
scenes rendered slow, window contents changed not well and many problems with it now

**Comment by gameknife** [comment]
did you mean that, benchmark sample should begin after scene is fully ready, currently, it samples some bad frame, so it makes the final result slower?

**Comment by tigrazone** [comment]
call
gkNextRenderer --present-mode 0 --benchmark --next-scenes
and you can see

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/3e06f222c163f8fa9b607bb100fad04580b5fc32

**Comment by tigrazone** [comment]
Thank you!
