### ISSUE TITLE
russian text issue

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#57]
It is well knownl issue and I dont know how to fix it
https://github.com/ocornut/imgui/issues/609
![ru](https://github.com/user-attachments/assets/1f42827b-ef20-44e5-9f43-5c59d3d5c7b7)

**Comment by gameknife** [comment]
russian characters display on my pc / mac / steamdeck is ok, I doubt this is your local compiler problem?
you can download this https://github.com/gameknife/gkNextRenderer/releases/tag/v0.1.0.7
and try

**Comment by tigrazone** [comment]
Dont know. I'm live in Ukraine and use russian as native language and half of programs on russian. And my windows 10 on russian

**Comment by tigrazone** [comment]
gkNextRenderer.exe --locale RU works ok
gkNextRenderer.exe --locale ru output ????????
strange issue
RU.txt is assets/locale file name
