### ISSUE TITLE
frames per second counter is broken?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#6]
in [RayTracingInVulkan](https://github.com/gameknife/RayTracingInVulkan) I change number of bounces but fps counter is still 59-60 with ANY SCENE. I try on 3060 laptop.
Is it error or it's ok?
I also try to set Temporary Steps to 2-8 and fps counter not changed.
I think, in [gkNextRenderer](https://github.com/gameknife/gkNextRenderer) used same code for recursive path tracing cycle(is it faster then for cycle?) and same fps counter code.
Please check

**Comment by gameknife** [comment]
--present-mode=0, disable the vsync

**Comment by tigrazone** [comment]
Is your created by defines recursive path tracing cycle are faster then cycle by tor operator?

**Comment by gameknife** [comment]
> Is your created by defines recursive path tracing cycle are faster then cycle by for operator?

the define recursive and for will not affect the performance,
you mentioned the fps at 59-60, it will be the vsync.

but I have a different impl: 
the default bounce time is set to 4, but it is not enough for refraction material, so I add a 
`ray.BounceCount--;` to refraction material, to get more bounce for specific materials, but others still limited to default bounce time
