### ISSUE TITLE
Feature request: select object with ctrl-click

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#62]
And you can use ImGuizmo as used in https://github.com/knightcrawler25/GLSL-PathTracer/

**Comment by tigrazone** [comment]
For show selected object you can use idea from https://github.com/nvpro-samples/vk_gltf_renderer/blob/master/shaders/silhouette.comp.glsl

**Comment by gameknife** [comment]
editor feature may consider this, thank you!
