### ISSUE TITLE
Feature requset: save HDR of untonemapped rendered image

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#63]
Idea is ability to save HDR image of rendered before tonemapping

**Comment by gameknife** [comment]
currently, when you using hdr monitor, avif is using the ST2084, it is a standard hdr output supportted by all many devices.
when using sdr monitor, the saved image is tonemapped currently, I will consider a better output options.

Maybe I should add a tempbuffer before the swapchain
