### ISSUE TITLE
how object selection is work?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#65]
I tried selection display but when I switch scene some object already selected.
Maybe you not implement cleaning of selected object id when scene is changed.
Select works for me by space. But not always select correct

**Comment by tigrazone** [comment]
Oh i see you do hardcoded coord 540, 540

**Comment by gameknife** [comment]
basic functional with https://github.com/gameknife/gkNextRenderer/commit/8aebf37c212275efbb5b896cf6f86cdf6bc74550

but not full funcional now~
