### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#7]
https://github.com/gameknife/gkNextRenderer/blob/bbb414c6db0adcdba63f2e3a99b448b1828f30e3/assets/shaders/Scatter.glsl#L33
but here is
https://github.com/gameknife/gkNextRenderer/blob/bbb414c6db0adcdba63f2e3a99b448b1828f30e3/assets/shaders/HybridDeferredShading.comp#L225

Which variant is correct?
cos(0.5f / 180.f * 3.14159f)
or
cos(0.25f / 180.f * 3.14159f)
???

**Comment by gameknife** [comment]
just magic number... like the "sun angle" in UnrealEngine, for soft shadow penumbra
