### ISSUE TITLE
How you create release builds?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#71]
I seen is exists .github/workflows but how to use it?
Please describe release build process

**Comment by tigrazone** [comment]
@santos-naudiyal spam, scam!!!!!

**Comment by gameknife** [comment]
all things done on this file
https://github.com/gameknife/gkNextRenderer/blob/main/.github/workflows/release.yml

it will be execute by push tag begin with 'v'

**Comment by tigrazone** [comment]
I have error with actions in my private repo.
I added 
`    permissions: write-all`
to all files
Maybe you tune up github token somehow?
![git-actions1](https://github.com/user-attachments/assets/ddfe1ea6-4da6-4cf3-a83f-d1a50702cc63)

**Comment by gameknife** [comment]
it is a marco secrets.GITHUB_TOKEN
maybe you should create it in your personal or repo settings?

**Comment by tigrazone** [comment]
> it is a marco secrets.GITHUB_TOKEN
> maybe you should create it in your personal or repo settings?
I dont understand where this must be created

I set these settings for actions:
![act-perm1](https://github.com/user-attachments/assets/5d45d65f-e3df-4bae-b815-c540d416e68f)

And I have same error after set it all
[make-release](https://github.com/tigrazone/gkNextRenderer-my-private/actions/runs/10907219687/job/30270343721#step:3:10)
Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}

**Comment by gameknife** [comment]
maybe you create a duplicate release? tag_name, release_name already exist?

**Comment by tigrazone** [comment]
no

**Comment by gameknife** [comment]
release action works perfect, please check the official documents~
