### ISSUE TITLE
How to add library from vcpkg?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#72]
I want to add nativefiledialog-extended.
What to do and which files I must to change and how?
Thank you

**Comment by gameknife** [comment]
you can refer this commit, add library to vcpkg_xxx.sh/bat, add the requirement in cmakelist.txt, then build all platforms or use marco to divide.

https://github.com/gameknife/gkNextRenderer/commit/23d7425c565322cb1aae08c07d1b790527fdc209#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4

**Comment by tigrazone** [comment]
one more question.
where you check(URL of page) name of package?

**Comment by gameknife** [comment]
https://vcpkg.link/

**Comment by tigrazone** [comment]
Hmm work strange
vcpkg install nativefiledialog-extended
Computing installation plan...
error: while looking for nativefiledialog-extended:x64-windows:
C:\msys64\home\user\from-git\gkNextRenderer-my-private\build\vcpkg.windows\ports\nativefiledialog-extended: error: nativefiledialog-extended does not exist

[https://vcpkg.link/ports/nativefiledialog-extended](https://vcpkg.link/ports/nativefiledialog-extended)

**Comment by gameknife** [comment]
you use general windows environment or mingw?

**Comment by tigrazone** [comment]
I use VS, for windows. Mingw is work with issues for me and I dont want to use it now with gkNextRenderer

**Comment by tigrazone** [comment]
I used mingw before often and I have as usual folders structure like C:\msys64\home\user\from-git\
But with gkNextRenderer I use VS

**Comment by gameknife** [comment]
the vcpkg.bat should be execute from general console of windows, mingw env may failed? I didn't try it

**Comment by tigrazone** [comment]
I use cmd.exe
I dont use mingw now
