### ISSUE TITLE
Feature request: OIDN for RayQuery, SVGF denoiser maybe

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#73]

**Comment by gameknife** [comment]
oidn is not stable for moving images, svgf is considering, currently my main job is a little busy, and some time was taken from BlackMyth: Wukong. SVGF will be next key feature in my todolist!

**Comment by gameknife** [comment]
latest commit, I introduce jbf in final compose, to denoise the temporal results. SVGF is a little bit conflict with previous work. The result is acceptable even on motion images.

And oidn is competible with ray query renderer, too.

I would like to remove the ray tracing pipeline renderer, as it is not efficient than rayquery renderer, and it takes more work to maintiance.
