### ISSUE TITLE
use  #ifdef __cplusplus

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#77]
it is better than
https://github.com/gameknife/gkNextRenderer/blob/412cb9d61fcff27f074eff9079cf349eb9692f78/assets/shaders/common/UniformBufferObject.glsl#L1

idea from [nvpro-samples/vk_raytrace/shaders/compress.glsl](https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/compress.glsl)

**Comment by gameknife** [comment]
great! fixed in https://github.com/gameknife/gkNextRenderer/commit/c098f45dedf25b4256b18ec9856ae8b546288414
