### ISSUE TITLE
RayQuery renderer in new release is slower than previous releases

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#81]
I checked in benchmarks with same models files from release 1.0.9 (get assets/models from 1.0.9 and replace 1.0.8 and 1.0.7 same folder to newer) and I see new release RayQuery renderer works slower.
[zip with reports](https://drive.google.com/file/d/1wqoJvXuKFlRHaNxUIa3KZq3RuKEve5Vl/view?usp=sharing)
Can you revert to fastest version in new release?

**Comment by tigrazone** [comment]
one more question. how to off denoiser in benchmark mode?
seems in benchmark node used not 1 Samples per pixel. maybe 2. 
when I off denoiser in renderer mode, not in benchmark mode and set Samples to 1 then speed of renderer start to be like in previous version. but slower little bit

**Comment by gameknife** [comment]
new jbf denoiser is default on, the cost is acceptable and make a quality boost. I will change --denoiser to --nodenoiser in the commandline

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/0cc51b83418333f432d06ed82a495463f920a249
