### ISSUE TITLE
strange noise on upper and left window borders - maybe issue with image area coords

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#82]
take look at video
https://youtu.be/niTqQK6EN4c

**Comment by tigrazone** [comment]
pattern also seen when I use --benchmark --next-scenes --savefile
![Still](https://github.com/user-attachments/assets/3d9cc942-e24b-47d3-8bdb-c608c9c175a5)
![Simple](https://github.com/user-attachments/assets/a15f8389-0267-4c6d-baf1-d9b533571f90)
![Ray Tracing In One Weekend](https://github.com/user-attachments/assets/bbe955d0-a444-4791-9950-b2681004bbff)
![Qx50](https://github.com/user-attachments/assets/5c7d5c9f-2155-40e1-903c-ff1b3b1a1dbf)
![LuxBall](https://github.com/user-attachments/assets/27e3fd98-3bb7-49aa-a8a4-015552958eb6)
![LowpolyTrack](https://github.com/user-attachments/assets/8e873b68-08ae-4cff-8c2d-6e09950f30b8)
![LivingRoom](https://github.com/user-attachments/assets/fcb97449-9918-4950-8586-ccb3d04328ca)
![Kitchen](https://github.com/user-attachments/assets/a83bf293-5d84-4b80-821b-dfd5a59af1e7)
![Complex](https://github.com/user-attachments/assets/e02ae221-ac03-49ec-8f2e-d03d0097e5c8)

**Comment by gameknife** [comment]
this issue introduced with the render region, I will try to fix it

**Comment by gameknife** [comment]
fixed in https://github.com/gameknife/gkNextRenderer/commit/0cc51b83418333f432d06ed82a495463f920a249
