### ISSUE TITLE
what a sense to use 2 modelCounts?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#85]
you use this variables in 2 places:
here
https://github.com/gameknife/gkNextRenderer/blob/f3a2ec57ec93d67f5d3dd2e79e848f3af84feea7/src/Assets/Scene.cpp#L75

and here
https://github.com/gameknife/gkNextRenderer/blob/f3a2ec57ec93d67f5d3dd2e79e848f3af84feea7/src/Assets/Scene.cpp#L78

can it be rewriten without use variable with same name?
looks weird

and why use int and uint32_t?
maybe for first variable name use modelCounts0, for second modelCounts?

**Comment by gameknife** [comment]
good question, totally misunderstanding, fix in https://github.com/gameknife/gkNextRenderer/commit/be5a322da7f795f78c0cbaf929a6b9945a85be54
