### ISSUE TITLE
Feature request: switch renderer on fly

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#88]
select from UI, for example

**Comment by gameknife** [comment]
currently, decoupled application & renderer have will made this, add to my todolist

**Comment by gameknife** [comment]
working on feature/logic-render

**Comment by tigrazone** [comment]
where is switch in UI?

**Comment by gameknife** [comment]
when it merge into dev 😆

**Comment by gameknife** [comment]
merged in https://github.com/gameknife/gkNextRenderer/commit/545289940fa7bd5b768d33e7f30618ee61bfddc2
