### ISSUE TITLE
Do you need my work to implement GLTF ascii support and packed Vertex stucture? I you need, I can do PR

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#90]

**Comment by gameknife** [comment]
did you mean use gltf bin data directly map to gpu buffer?
currently, if I want to compress vertex, the Asset::Vertex struct must be changed. But I'm doubting the performance will boost or not?

**Comment by tigrazone** [comment]
Performance is same but smaller memory amount. Gltf loaded as glb but data in texture files and gltf file and sometimes in bin file
