### ISSUE TITLE
seems sun doesnt work?

### ISSUE THREAD

**Issue by tigrazone** [gameknife/gkNextRenderer#95]
I checked code [before my first commit](https://github.com/gameknife/gkNextRenderer/tree/1f0eb7244c6ad3abc040f44accf56cb1d8309a08) and nothing is changed, like in last commits, when I try to change parameters with "Sun"

**Comment by gameknife** [comment]
sun is switchable, check simple scene, sun works properly

**Comment by tigrazone** [comment]
Maybe it is better to do for every scene show on knobs in ui is works or no, hasSun or no and can be switch on or off in any time
